"""empty message

Revision ID: 81417d4ddc6e
Revises: 
Create Date: 2023-12-30 16:31:51.677101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81417d4ddc6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fortune',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('qq', sa.BigInteger(), nullable=False),
    sa.Column('fortune', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fortune'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fortune')
    # ### end Alembic commands ###
