"""empty message

Revision ID: b8680951f738
Revises: 81417d4ddc6e
Create Date: 2023-12-30 16:41:20.176071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8680951f738'
down_revision = '81417d4ddc6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fortune', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fortune', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.String(length=20),
               type_=mysql.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
