version: '3.7'

services:
  mysql:
    image: mysql:8
    expose:
      - 3306
    volumes:
      - ./build/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nonebot
    networks:
      - network
    ports:
      - 9001:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9000:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 10G
    networks:
      - network
  redis:
    image: redis:6
    ports:
      - 9002:6379
    networks:
      - network

networks:
  network:
    driver: bridge
