FROM mcr.microsoft.com/playwright:v1.29.0-focal

SHELL ["/bin/bash", "-c"]

WORKDIR /app

ENV PORT=8080

RUN apt-get update

RUN apt-get install -y python3.9 python3.9-venv

COPY requirements.txt /app/requirements.txt

RUN python3.9 -m venv venv

RUN source venv/bin/activate

RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN rm requirements.txt

RUN playwright install --with-deps

COPY ./ /app/

CMD uvicorn --workers 1 --env-file .env.prod --port 8080 --host 0.0.0.0 bot:app
