[tool.poetry]
name = "sevenrealms-bot"
version = "0.1.0"
description = ""
authors = ["Zeithrold <zeithrold@gmail.com>"]
readme = "README.md"
packages = [{ include = "sevenrealms_bot" }]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.0.0rc2"
uvicorn = "^0.20.0"
ghapi = "^1.0.3"
pony = "^0.7.16"
pymysql = "^1.0.2"
nonebot-adapter-onebot = "^2.2.0"
nonebot-adapter-github = "^0.2.5"
nonebot-plugin-status = "^0.6.0"
fastapi = "^0.89.1"
websockets = "^10.4"
nonebot-plugin-apscheduler = "^0.2.0"
aliyun-python-sdk-alinlp = "^1.0.16"
oss2 = "^2.16.0"
pandas = "^1.5.3"
py7zr = "^0.20.2"

[tool.nonebot]
# plugins = ["nonebot_plugin_status", "nonebot_plugin_apscheduler"]
plugins = [
    "nonebot_plugin_status",
    "nonebot_plugin_apscheduler",
    "nonebot_plugin_simplemusic",
    "nonebot_plugin_miragetank",
    "nonebot_plugin_bilibili_viode",
    "nonebot_plugin_datastore",
    "nonebot_plugin_dialectlist",
    "nonebot_plugin_maimai",
    "nonebot_plugin_groupmate_waifu",
    "nonebot_plugin_setu_collection",
    "nonebot_plugin_remove_bg",
    "nonebot_plugin_jrrp2",
    "nonebot_plugin_pjsk",
    "nonebot_plugin_group_whitelist",
]
plugin_dirs = ["sevenrealms_bot/plugins"]

[tool.poetry.group.dev.dependencies]
nb-cli = "^0.6.9"
autopep8 = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
