"""empty message

Revision ID: 942aaf44b53e
Revises: 
Create Date: 2023-12-29 12:18:19.098489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '942aaf44b53e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(length=64), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('alia')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alia', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('alias')

    # ### end Alembic commands ###
